package com.weigandtconsulting.javaschool.db.hibernate.entity;
// Generated Oct 28, 2015 4:51:35 PM by Hibernate Tools 4.3.1



/**
 * CustomerAddr generated by hbm2java
 */
public class CustomerAddr  implements java.io.Serializable {


     private int addr;
     private CustomerMaster customerMaster;
     private DeliveryPoint deliveryPoint;
     private String addrType;
     private boolean primaryInd;
     private String gln;
     private String region;
     private String city;
     private String postalCode;
     private String countryCode;
     private String address1;
     private String address2;
     private String address3;
     private String contactName;
     private String contactPhone;
     private String contactFax;
     private String contactEmail;

    public CustomerAddr() {
    }

	
    public CustomerAddr(int addr, CustomerMaster customerMaster, DeliveryPoint deliveryPoint, String addrType, boolean primaryInd, String region, String city, String countryCode, String address1) {
        this.addr = addr;
        this.customerMaster = customerMaster;
        this.deliveryPoint = deliveryPoint;
        this.addrType = addrType;
        this.primaryInd = primaryInd;
        this.region = region;
        this.city = city;
        this.countryCode = countryCode;
        this.address1 = address1;
    }
    public CustomerAddr(int addr, CustomerMaster customerMaster, DeliveryPoint deliveryPoint, String addrType, boolean primaryInd, String gln, String region, String city, String postalCode, String countryCode, String address1, String address2, String address3, String contactName, String contactPhone, String contactFax, String contactEmail) {
       this.addr = addr;
       this.customerMaster = customerMaster;
       this.deliveryPoint = deliveryPoint;
       this.addrType = addrType;
       this.primaryInd = primaryInd;
       this.gln = gln;
       this.region = region;
       this.city = city;
       this.postalCode = postalCode;
       this.countryCode = countryCode;
       this.address1 = address1;
       this.address2 = address2;
       this.address3 = address3;
       this.contactName = contactName;
       this.contactPhone = contactPhone;
       this.contactFax = contactFax;
       this.contactEmail = contactEmail;
    }
   
    public int getAddr() {
        return this.addr;
    }
    
    public void setAddr(int addr) {
        this.addr = addr;
    }
    public CustomerMaster getCustomerMaster() {
        return this.customerMaster;
    }
    
    public void setCustomerMaster(CustomerMaster customerMaster) {
        this.customerMaster = customerMaster;
    }
    public DeliveryPoint getDeliveryPoint() {
        return this.deliveryPoint;
    }
    
    public void setDeliveryPoint(DeliveryPoint deliveryPoint) {
        this.deliveryPoint = deliveryPoint;
    }
    public String getAddrType() {
        return this.addrType;
    }
    
    public void setAddrType(String addrType) {
        this.addrType = addrType;
    }
    public boolean isPrimaryInd() {
        return this.primaryInd;
    }
    
    public void setPrimaryInd(boolean primaryInd) {
        this.primaryInd = primaryInd;
    }
    public String getGln() {
        return this.gln;
    }
    
    public void setGln(String gln) {
        this.gln = gln;
    }
    public String getRegion() {
        return this.region;
    }
    
    public void setRegion(String region) {
        this.region = region;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getPostalCode() {
        return this.postalCode;
    }
    
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }
    public String getCountryCode() {
        return this.countryCode;
    }
    
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }
    public String getAddress1() {
        return this.address1;
    }
    
    public void setAddress1(String address1) {
        this.address1 = address1;
    }
    public String getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }
    public String getAddress3() {
        return this.address3;
    }
    
    public void setAddress3(String address3) {
        this.address3 = address3;
    }
    public String getContactName() {
        return this.contactName;
    }
    
    public void setContactName(String contactName) {
        this.contactName = contactName;
    }
    public String getContactPhone() {
        return this.contactPhone;
    }
    
    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone;
    }
    public String getContactFax() {
        return this.contactFax;
    }
    
    public void setContactFax(String contactFax) {
        this.contactFax = contactFax;
    }
    public String getContactEmail() {
        return this.contactEmail;
    }
    
    public void setContactEmail(String contactEmail) {
        this.contactEmail = contactEmail;
    }




}


