package com.weigandtconsulting.javaschool.db.hibernate.entity;
// Generated Oct 28, 2015 4:51:35 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CustomerMaster generated by hbm2java
 */
public class CustomerMaster  implements java.io.Serializable {


     private long customer;
     private CustomerMaster customerMasterByBillToCustomer;
     private CustomerMaster customerMasterByCustomerParentId;
     private SalesAgent salesAgentByKamId;
     private SalesAgent salesAgentBySaId;
     private String customerName;
     private String customerName2;
     private String customerName3;
     private String customerName4;
     private String customerStatus;
     private String prevStatus;
     private String customerType;
     private Long channel;
     private long subchannel;
     private Long subchannelType;
     private Long customerGroup;
     private String customerHierarchy;
     private int lang;
     private boolean recyclingInd;
     private Long mainLocation;
     private boolean multiLocInd;
     private String accountGroup;
     private String taxNumber;
     private String custAccountNum;
     private String oib;
     private String currencyCode;
     private String orderCurrency;
     private boolean agrGroupInd;
     private boolean consInvInd;
     private Long consTimeframe;
     private Short invoiceLayout;
     private Short shippmentLayout;
     private boolean proofOfDelInd;
     private boolean assortItemInd;
     private boolean retPackageInd;
     private boolean assortFplInd;
     private boolean retOrderInd;
     private boolean podPriceInd;
     private boolean usageItemInd;
     private boolean ediOrderInd;
     private boolean ediInvoiceInd;
     private boolean ediReturnInd;
     private boolean ediPriceListInd;
     private boolean ediDispatchAdvInd;
     private boolean ediAsnInd;
     private boolean ediOrderConfInd;
     private boolean ediProofOfDelInd;
     private boolean invoiceVatInd;
     private Long x;
     private long y;
     private String insuranceInstitution;
     private String comments;
     private String auxCompanyCode;
     private String auxGlAccount;
     private String auxShortName;
     private Date creDate;
     private String creId;
     private Date approvalDate;
     private String approvalId;
     private Date inactiveDate;
     private String inactiveId;
     private Date modDate;
     private String modId;
     private Date blockDate;
     private String blockId;
     private String vatNumber;
     private boolean vatLiable;
     private Long noVatReason;
     private boolean customerPlusmInd;
     private boolean ediInvoiceByMailInd;
     private Set deliveryPoints = new HashSet(0);
     private Set customerContracts = new HashSet(0);
     private Set customerMastersForBillToCustomer = new HashSet(0);
     private Set customerMastersForCustomerParentId = new HashSet(0);
     private Set customerAddrs = new HashSet(0);

    public CustomerMaster() {
    }

	
    public CustomerMaster(long customer, String customerName, String customerStatus, String prevStatus, String customerType, long subchannel, String customerHierarchy, int lang, boolean recyclingInd, boolean multiLocInd, String accountGroup, boolean agrGroupInd, boolean consInvInd, boolean proofOfDelInd, boolean assortItemInd, boolean retPackageInd, boolean assortFplInd, boolean retOrderInd, boolean podPriceInd, boolean usageItemInd, boolean ediOrderInd, boolean ediInvoiceInd, boolean ediReturnInd, boolean ediPriceListInd, boolean ediDispatchAdvInd, boolean ediAsnInd, boolean ediOrderConfInd, boolean ediProofOfDelInd, boolean invoiceVatInd, long y, Date creDate, String creId, Date modDate, String modId, boolean vatLiable, boolean customerPlusmInd, boolean ediInvoiceByMailInd) {
        this.customer = customer;
        this.customerName = customerName;
        this.customerStatus = customerStatus;
        this.prevStatus = prevStatus;
        this.customerType = customerType;
        this.subchannel = subchannel;
        this.customerHierarchy = customerHierarchy;
        this.lang = lang;
        this.recyclingInd = recyclingInd;
        this.multiLocInd = multiLocInd;
        this.accountGroup = accountGroup;
        this.agrGroupInd = agrGroupInd;
        this.consInvInd = consInvInd;
        this.proofOfDelInd = proofOfDelInd;
        this.assortItemInd = assortItemInd;
        this.retPackageInd = retPackageInd;
        this.assortFplInd = assortFplInd;
        this.retOrderInd = retOrderInd;
        this.podPriceInd = podPriceInd;
        this.usageItemInd = usageItemInd;
        this.ediOrderInd = ediOrderInd;
        this.ediInvoiceInd = ediInvoiceInd;
        this.ediReturnInd = ediReturnInd;
        this.ediPriceListInd = ediPriceListInd;
        this.ediDispatchAdvInd = ediDispatchAdvInd;
        this.ediAsnInd = ediAsnInd;
        this.ediOrderConfInd = ediOrderConfInd;
        this.ediProofOfDelInd = ediProofOfDelInd;
        this.invoiceVatInd = invoiceVatInd;
        this.y = y;
        this.creDate = creDate;
        this.creId = creId;
        this.modDate = modDate;
        this.modId = modId;
        this.vatLiable = vatLiable;
        this.customerPlusmInd = customerPlusmInd;
        this.ediInvoiceByMailInd = ediInvoiceByMailInd;
    }
    public CustomerMaster(long customer, CustomerMaster customerMasterByBillToCustomer, CustomerMaster customerMasterByCustomerParentId, SalesAgent salesAgentByKamId, SalesAgent salesAgentBySaId, String customerName, String customerName2, String customerName3, String customerName4, String customerStatus, String prevStatus, String customerType, Long channel, long subchannel, Long subchannelType, Long customerGroup, String customerHierarchy, int lang, boolean recyclingInd, Long mainLocation, boolean multiLocInd, String accountGroup, String taxNumber, String custAccountNum, String oib, String currencyCode, String orderCurrency, boolean agrGroupInd, boolean consInvInd, Long consTimeframe, Short invoiceLayout, Short shippmentLayout, boolean proofOfDelInd, boolean assortItemInd, boolean retPackageInd, boolean assortFplInd, boolean retOrderInd, boolean podPriceInd, boolean usageItemInd, boolean ediOrderInd, boolean ediInvoiceInd, boolean ediReturnInd, boolean ediPriceListInd, boolean ediDispatchAdvInd, boolean ediAsnInd, boolean ediOrderConfInd, boolean ediProofOfDelInd, boolean invoiceVatInd, Long x, long y, String insuranceInstitution, String comments, String auxCompanyCode, String auxGlAccount, String auxShortName, Date creDate, String creId, Date approvalDate, String approvalId, Date inactiveDate, String inactiveId, Date modDate, String modId, Date blockDate, String blockId, String vatNumber, boolean vatLiable, Long noVatReason, boolean customerPlusmInd, boolean ediInvoiceByMailInd, Set deliveryPoints, Set customerContracts, Set customerMastersForBillToCustomer, Set customerMastersForCustomerParentId, Set customerAddrs) {
       this.customer = customer;
       this.customerMasterByBillToCustomer = customerMasterByBillToCustomer;
       this.customerMasterByCustomerParentId = customerMasterByCustomerParentId;
       this.salesAgentByKamId = salesAgentByKamId;
       this.salesAgentBySaId = salesAgentBySaId;
       this.customerName = customerName;
       this.customerName2 = customerName2;
       this.customerName3 = customerName3;
       this.customerName4 = customerName4;
       this.customerStatus = customerStatus;
       this.prevStatus = prevStatus;
       this.customerType = customerType;
       this.channel = channel;
       this.subchannel = subchannel;
       this.subchannelType = subchannelType;
       this.customerGroup = customerGroup;
       this.customerHierarchy = customerHierarchy;
       this.lang = lang;
       this.recyclingInd = recyclingInd;
       this.mainLocation = mainLocation;
       this.multiLocInd = multiLocInd;
       this.accountGroup = accountGroup;
       this.taxNumber = taxNumber;
       this.custAccountNum = custAccountNum;
       this.oib = oib;
       this.currencyCode = currencyCode;
       this.orderCurrency = orderCurrency;
       this.agrGroupInd = agrGroupInd;
       this.consInvInd = consInvInd;
       this.consTimeframe = consTimeframe;
       this.invoiceLayout = invoiceLayout;
       this.shippmentLayout = shippmentLayout;
       this.proofOfDelInd = proofOfDelInd;
       this.assortItemInd = assortItemInd;
       this.retPackageInd = retPackageInd;
       this.assortFplInd = assortFplInd;
       this.retOrderInd = retOrderInd;
       this.podPriceInd = podPriceInd;
       this.usageItemInd = usageItemInd;
       this.ediOrderInd = ediOrderInd;
       this.ediInvoiceInd = ediInvoiceInd;
       this.ediReturnInd = ediReturnInd;
       this.ediPriceListInd = ediPriceListInd;
       this.ediDispatchAdvInd = ediDispatchAdvInd;
       this.ediAsnInd = ediAsnInd;
       this.ediOrderConfInd = ediOrderConfInd;
       this.ediProofOfDelInd = ediProofOfDelInd;
       this.invoiceVatInd = invoiceVatInd;
       this.x = x;
       this.y = y;
       this.insuranceInstitution = insuranceInstitution;
       this.comments = comments;
       this.auxCompanyCode = auxCompanyCode;
       this.auxGlAccount = auxGlAccount;
       this.auxShortName = auxShortName;
       this.creDate = creDate;
       this.creId = creId;
       this.approvalDate = approvalDate;
       this.approvalId = approvalId;
       this.inactiveDate = inactiveDate;
       this.inactiveId = inactiveId;
       this.modDate = modDate;
       this.modId = modId;
       this.blockDate = blockDate;
       this.blockId = blockId;
       this.vatNumber = vatNumber;
       this.vatLiable = vatLiable;
       this.noVatReason = noVatReason;
       this.customerPlusmInd = customerPlusmInd;
       this.ediInvoiceByMailInd = ediInvoiceByMailInd;
       this.deliveryPoints = deliveryPoints;
       this.customerContracts = customerContracts;
       this.customerMastersForBillToCustomer = customerMastersForBillToCustomer;
       this.customerMastersForCustomerParentId = customerMastersForCustomerParentId;
       this.customerAddrs = customerAddrs;
    }
   
    public long getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(long customer) {
        this.customer = customer;
    }
    public CustomerMaster getCustomerMasterByBillToCustomer() {
        return this.customerMasterByBillToCustomer;
    }
    
    public void setCustomerMasterByBillToCustomer(CustomerMaster customerMasterByBillToCustomer) {
        this.customerMasterByBillToCustomer = customerMasterByBillToCustomer;
    }
    public CustomerMaster getCustomerMasterByCustomerParentId() {
        return this.customerMasterByCustomerParentId;
    }
    
    public void setCustomerMasterByCustomerParentId(CustomerMaster customerMasterByCustomerParentId) {
        this.customerMasterByCustomerParentId = customerMasterByCustomerParentId;
    }
    public SalesAgent getSalesAgentByKamId() {
        return this.salesAgentByKamId;
    }
    
    public void setSalesAgentByKamId(SalesAgent salesAgentByKamId) {
        this.salesAgentByKamId = salesAgentByKamId;
    }
    public SalesAgent getSalesAgentBySaId() {
        return this.salesAgentBySaId;
    }
    
    public void setSalesAgentBySaId(SalesAgent salesAgentBySaId) {
        this.salesAgentBySaId = salesAgentBySaId;
    }
    public String getCustomerName() {
        return this.customerName;
    }
    
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }
    public String getCustomerName2() {
        return this.customerName2;
    }
    
    public void setCustomerName2(String customerName2) {
        this.customerName2 = customerName2;
    }
    public String getCustomerName3() {
        return this.customerName3;
    }
    
    public void setCustomerName3(String customerName3) {
        this.customerName3 = customerName3;
    }
    public String getCustomerName4() {
        return this.customerName4;
    }
    
    public void setCustomerName4(String customerName4) {
        this.customerName4 = customerName4;
    }
    public String getCustomerStatus() {
        return this.customerStatus;
    }
    
    public void setCustomerStatus(String customerStatus) {
        this.customerStatus = customerStatus;
    }
    public String getPrevStatus() {
        return this.prevStatus;
    }
    
    public void setPrevStatus(String prevStatus) {
        this.prevStatus = prevStatus;
    }
    public String getCustomerType() {
        return this.customerType;
    }
    
    public void setCustomerType(String customerType) {
        this.customerType = customerType;
    }
    public Long getChannel() {
        return this.channel;
    }
    
    public void setChannel(Long channel) {
        this.channel = channel;
    }
    public long getSubchannel() {
        return this.subchannel;
    }
    
    public void setSubchannel(long subchannel) {
        this.subchannel = subchannel;
    }
    public Long getSubchannelType() {
        return this.subchannelType;
    }
    
    public void setSubchannelType(Long subchannelType) {
        this.subchannelType = subchannelType;
    }
    public Long getCustomerGroup() {
        return this.customerGroup;
    }
    
    public void setCustomerGroup(Long customerGroup) {
        this.customerGroup = customerGroup;
    }
    public String getCustomerHierarchy() {
        return this.customerHierarchy;
    }
    
    public void setCustomerHierarchy(String customerHierarchy) {
        this.customerHierarchy = customerHierarchy;
    }
    public int getLang() {
        return this.lang;
    }
    
    public void setLang(int lang) {
        this.lang = lang;
    }
    public boolean isRecyclingInd() {
        return this.recyclingInd;
    }
    
    public void setRecyclingInd(boolean recyclingInd) {
        this.recyclingInd = recyclingInd;
    }
    public Long getMainLocation() {
        return this.mainLocation;
    }
    
    public void setMainLocation(Long mainLocation) {
        this.mainLocation = mainLocation;
    }
    public boolean isMultiLocInd() {
        return this.multiLocInd;
    }
    
    public void setMultiLocInd(boolean multiLocInd) {
        this.multiLocInd = multiLocInd;
    }
    public String getAccountGroup() {
        return this.accountGroup;
    }
    
    public void setAccountGroup(String accountGroup) {
        this.accountGroup = accountGroup;
    }
    public String getTaxNumber() {
        return this.taxNumber;
    }
    
    public void setTaxNumber(String taxNumber) {
        this.taxNumber = taxNumber;
    }
    public String getCustAccountNum() {
        return this.custAccountNum;
    }
    
    public void setCustAccountNum(String custAccountNum) {
        this.custAccountNum = custAccountNum;
    }
    public String getOib() {
        return this.oib;
    }
    
    public void setOib(String oib) {
        this.oib = oib;
    }
    public String getCurrencyCode() {
        return this.currencyCode;
    }
    
    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode;
    }
    public String getOrderCurrency() {
        return this.orderCurrency;
    }
    
    public void setOrderCurrency(String orderCurrency) {
        this.orderCurrency = orderCurrency;
    }
    public boolean isAgrGroupInd() {
        return this.agrGroupInd;
    }
    
    public void setAgrGroupInd(boolean agrGroupInd) {
        this.agrGroupInd = agrGroupInd;
    }
    public boolean isConsInvInd() {
        return this.consInvInd;
    }
    
    public void setConsInvInd(boolean consInvInd) {
        this.consInvInd = consInvInd;
    }
    public Long getConsTimeframe() {
        return this.consTimeframe;
    }
    
    public void setConsTimeframe(Long consTimeframe) {
        this.consTimeframe = consTimeframe;
    }
    public Short getInvoiceLayout() {
        return this.invoiceLayout;
    }
    
    public void setInvoiceLayout(Short invoiceLayout) {
        this.invoiceLayout = invoiceLayout;
    }
    public Short getShippmentLayout() {
        return this.shippmentLayout;
    }
    
    public void setShippmentLayout(Short shippmentLayout) {
        this.shippmentLayout = shippmentLayout;
    }
    public boolean isProofOfDelInd() {
        return this.proofOfDelInd;
    }
    
    public void setProofOfDelInd(boolean proofOfDelInd) {
        this.proofOfDelInd = proofOfDelInd;
    }
    public boolean isAssortItemInd() {
        return this.assortItemInd;
    }
    
    public void setAssortItemInd(boolean assortItemInd) {
        this.assortItemInd = assortItemInd;
    }
    public boolean isRetPackageInd() {
        return this.retPackageInd;
    }
    
    public void setRetPackageInd(boolean retPackageInd) {
        this.retPackageInd = retPackageInd;
    }
    public boolean isAssortFplInd() {
        return this.assortFplInd;
    }
    
    public void setAssortFplInd(boolean assortFplInd) {
        this.assortFplInd = assortFplInd;
    }
    public boolean isRetOrderInd() {
        return this.retOrderInd;
    }
    
    public void setRetOrderInd(boolean retOrderInd) {
        this.retOrderInd = retOrderInd;
    }
    public boolean isPodPriceInd() {
        return this.podPriceInd;
    }
    
    public void setPodPriceInd(boolean podPriceInd) {
        this.podPriceInd = podPriceInd;
    }
    public boolean isUsageItemInd() {
        return this.usageItemInd;
    }
    
    public void setUsageItemInd(boolean usageItemInd) {
        this.usageItemInd = usageItemInd;
    }
    public boolean isEdiOrderInd() {
        return this.ediOrderInd;
    }
    
    public void setEdiOrderInd(boolean ediOrderInd) {
        this.ediOrderInd = ediOrderInd;
    }
    public boolean isEdiInvoiceInd() {
        return this.ediInvoiceInd;
    }
    
    public void setEdiInvoiceInd(boolean ediInvoiceInd) {
        this.ediInvoiceInd = ediInvoiceInd;
    }
    public boolean isEdiReturnInd() {
        return this.ediReturnInd;
    }
    
    public void setEdiReturnInd(boolean ediReturnInd) {
        this.ediReturnInd = ediReturnInd;
    }
    public boolean isEdiPriceListInd() {
        return this.ediPriceListInd;
    }
    
    public void setEdiPriceListInd(boolean ediPriceListInd) {
        this.ediPriceListInd = ediPriceListInd;
    }
    public boolean isEdiDispatchAdvInd() {
        return this.ediDispatchAdvInd;
    }
    
    public void setEdiDispatchAdvInd(boolean ediDispatchAdvInd) {
        this.ediDispatchAdvInd = ediDispatchAdvInd;
    }
    public boolean isEdiAsnInd() {
        return this.ediAsnInd;
    }
    
    public void setEdiAsnInd(boolean ediAsnInd) {
        this.ediAsnInd = ediAsnInd;
    }
    public boolean isEdiOrderConfInd() {
        return this.ediOrderConfInd;
    }
    
    public void setEdiOrderConfInd(boolean ediOrderConfInd) {
        this.ediOrderConfInd = ediOrderConfInd;
    }
    public boolean isEdiProofOfDelInd() {
        return this.ediProofOfDelInd;
    }
    
    public void setEdiProofOfDelInd(boolean ediProofOfDelInd) {
        this.ediProofOfDelInd = ediProofOfDelInd;
    }
    public boolean isInvoiceVatInd() {
        return this.invoiceVatInd;
    }
    
    public void setInvoiceVatInd(boolean invoiceVatInd) {
        this.invoiceVatInd = invoiceVatInd;
    }
    public Long getX() {
        return this.x;
    }
    
    public void setX(Long x) {
        this.x = x;
    }
    public long getY() {
        return this.y;
    }
    
    public void setY(long y) {
        this.y = y;
    }
    public String getInsuranceInstitution() {
        return this.insuranceInstitution;
    }
    
    public void setInsuranceInstitution(String insuranceInstitution) {
        this.insuranceInstitution = insuranceInstitution;
    }
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }
    public String getAuxCompanyCode() {
        return this.auxCompanyCode;
    }
    
    public void setAuxCompanyCode(String auxCompanyCode) {
        this.auxCompanyCode = auxCompanyCode;
    }
    public String getAuxGlAccount() {
        return this.auxGlAccount;
    }
    
    public void setAuxGlAccount(String auxGlAccount) {
        this.auxGlAccount = auxGlAccount;
    }
    public String getAuxShortName() {
        return this.auxShortName;
    }
    
    public void setAuxShortName(String auxShortName) {
        this.auxShortName = auxShortName;
    }
    public Date getCreDate() {
        return this.creDate;
    }
    
    public void setCreDate(Date creDate) {
        this.creDate = creDate;
    }
    public String getCreId() {
        return this.creId;
    }
    
    public void setCreId(String creId) {
        this.creId = creId;
    }
    public Date getApprovalDate() {
        return this.approvalDate;
    }
    
    public void setApprovalDate(Date approvalDate) {
        this.approvalDate = approvalDate;
    }
    public String getApprovalId() {
        return this.approvalId;
    }
    
    public void setApprovalId(String approvalId) {
        this.approvalId = approvalId;
    }
    public Date getInactiveDate() {
        return this.inactiveDate;
    }
    
    public void setInactiveDate(Date inactiveDate) {
        this.inactiveDate = inactiveDate;
    }
    public String getInactiveId() {
        return this.inactiveId;
    }
    
    public void setInactiveId(String inactiveId) {
        this.inactiveId = inactiveId;
    }
    public Date getModDate() {
        return this.modDate;
    }
    
    public void setModDate(Date modDate) {
        this.modDate = modDate;
    }
    public String getModId() {
        return this.modId;
    }
    
    public void setModId(String modId) {
        this.modId = modId;
    }
    public Date getBlockDate() {
        return this.blockDate;
    }
    
    public void setBlockDate(Date blockDate) {
        this.blockDate = blockDate;
    }
    public String getBlockId() {
        return this.blockId;
    }
    
    public void setBlockId(String blockId) {
        this.blockId = blockId;
    }
    public String getVatNumber() {
        return this.vatNumber;
    }
    
    public void setVatNumber(String vatNumber) {
        this.vatNumber = vatNumber;
    }
    public boolean isVatLiable() {
        return this.vatLiable;
    }
    
    public void setVatLiable(boolean vatLiable) {
        this.vatLiable = vatLiable;
    }
    public Long getNoVatReason() {
        return this.noVatReason;
    }
    
    public void setNoVatReason(Long noVatReason) {
        this.noVatReason = noVatReason;
    }
    public boolean isCustomerPlusmInd() {
        return this.customerPlusmInd;
    }
    
    public void setCustomerPlusmInd(boolean customerPlusmInd) {
        this.customerPlusmInd = customerPlusmInd;
    }
    public boolean isEdiInvoiceByMailInd() {
        return this.ediInvoiceByMailInd;
    }
    
    public void setEdiInvoiceByMailInd(boolean ediInvoiceByMailInd) {
        this.ediInvoiceByMailInd = ediInvoiceByMailInd;
    }
    public Set getDeliveryPoints() {
        return this.deliveryPoints;
    }
    
    public void setDeliveryPoints(Set deliveryPoints) {
        this.deliveryPoints = deliveryPoints;
    }
    public Set getCustomerContracts() {
        return this.customerContracts;
    }
    
    public void setCustomerContracts(Set customerContracts) {
        this.customerContracts = customerContracts;
    }
    public Set getCustomerMastersForBillToCustomer() {
        return this.customerMastersForBillToCustomer;
    }
    
    public void setCustomerMastersForBillToCustomer(Set customerMastersForBillToCustomer) {
        this.customerMastersForBillToCustomer = customerMastersForBillToCustomer;
    }
    public Set getCustomerMastersForCustomerParentId() {
        return this.customerMastersForCustomerParentId;
    }
    
    public void setCustomerMastersForCustomerParentId(Set customerMastersForCustomerParentId) {
        this.customerMastersForCustomerParentId = customerMastersForCustomerParentId;
    }
    public Set getCustomerAddrs() {
        return this.customerAddrs;
    }
    
    public void setCustomerAddrs(Set customerAddrs) {
        this.customerAddrs = customerAddrs;
    }

    @Override
    public String toString() {
        return "CustomerMaster{" + "customer=" + customer + ", customerName=" + customerName + ", customerName2=" + customerName2 + ", customerStatus=" + customerStatus + ", customerType=" + customerType + '}';
    }

}


