package com.weigandtconsulting.javaschool.db.hibernate.entity;
// Generated Oct 28, 2015 4:51:35 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CustomerContract generated by hbm2java
 */
public class CustomerContract  implements java.io.Serializable {


     private BigDecimal contract;
     private CustomerContract customerContract;
     private CustomerMaster customerMaster;
     private String description;
     private String status;
     private BigDecimal credit;
     private String insDescription;
     private BigDecimal insAmount;
     private String currencyCode;
     private boolean spcAssortment;
     private boolean customerLevelPp;
     private Date startDate;
     private Date endDate;
     private Date creDate;
     private String creId;
     private Date modDate;
     private String modId;
     private Date approvalDate;
     private String approvalId;
     private boolean exclusivityInd;
     private String prevStatus;
     private Date cancelDate;
     private String cancelId;
     private String exContractId;
     private boolean invoiceWithoutVat;
     private Set customerContracts = new HashSet(0);
     private ContractPricingPriority contractPricingPriority;

    public CustomerContract() {
    }

	
    public CustomerContract(BigDecimal contract, CustomerMaster customerMaster, String description, String status, BigDecimal credit, String currencyCode, boolean spcAssortment, boolean customerLevelPp, Date startDate, Date endDate, Date creDate, String creId, Date modDate, String modId, boolean exclusivityInd, String prevStatus, boolean invoiceWithoutVat) {
        this.contract = contract;
        this.customerMaster = customerMaster;
        this.description = description;
        this.status = status;
        this.credit = credit;
        this.currencyCode = currencyCode;
        this.spcAssortment = spcAssortment;
        this.customerLevelPp = customerLevelPp;
        this.startDate = startDate;
        this.endDate = endDate;
        this.creDate = creDate;
        this.creId = creId;
        this.modDate = modDate;
        this.modId = modId;
        this.exclusivityInd = exclusivityInd;
        this.prevStatus = prevStatus;
        this.invoiceWithoutVat = invoiceWithoutVat;
    }
    public CustomerContract(BigDecimal contract, CustomerContract customerContract, CustomerMaster customerMaster, String description, String status, BigDecimal credit, String insDescription, BigDecimal insAmount, String currencyCode, boolean spcAssortment, boolean customerLevelPp, Date startDate, Date endDate, Date creDate, String creId, Date modDate, String modId, Date approvalDate, String approvalId, boolean exclusivityInd, String prevStatus, Date cancelDate, String cancelId, String exContractId, boolean invoiceWithoutVat, Set customerContracts, ContractPricingPriority contractPricingPriority) {
       this.contract = contract;
       this.customerContract = customerContract;
       this.customerMaster = customerMaster;
       this.description = description;
       this.status = status;
       this.credit = credit;
       this.insDescription = insDescription;
       this.insAmount = insAmount;
       this.currencyCode = currencyCode;
       this.spcAssortment = spcAssortment;
       this.customerLevelPp = customerLevelPp;
       this.startDate = startDate;
       this.endDate = endDate;
       this.creDate = creDate;
       this.creId = creId;
       this.modDate = modDate;
       this.modId = modId;
       this.approvalDate = approvalDate;
       this.approvalId = approvalId;
       this.exclusivityInd = exclusivityInd;
       this.prevStatus = prevStatus;
       this.cancelDate = cancelDate;
       this.cancelId = cancelId;
       this.exContractId = exContractId;
       this.invoiceWithoutVat = invoiceWithoutVat;
       this.customerContracts = customerContracts;
       this.contractPricingPriority = contractPricingPriority;
    }
   
    public BigDecimal getContract() {
        return this.contract;
    }
    
    public void setContract(BigDecimal contract) {
        this.contract = contract;
    }
    public CustomerContract getCustomerContract() {
        return this.customerContract;
    }
    
    public void setCustomerContract(CustomerContract customerContract) {
        this.customerContract = customerContract;
    }
    public CustomerMaster getCustomerMaster() {
        return this.customerMaster;
    }
    
    public void setCustomerMaster(CustomerMaster customerMaster) {
        this.customerMaster = customerMaster;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public BigDecimal getCredit() {
        return this.credit;
    }
    
    public void setCredit(BigDecimal credit) {
        this.credit = credit;
    }
    public String getInsDescription() {
        return this.insDescription;
    }
    
    public void setInsDescription(String insDescription) {
        this.insDescription = insDescription;
    }
    public BigDecimal getInsAmount() {
        return this.insAmount;
    }
    
    public void setInsAmount(BigDecimal insAmount) {
        this.insAmount = insAmount;
    }
    public String getCurrencyCode() {
        return this.currencyCode;
    }
    
    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode;
    }
    public boolean isSpcAssortment() {
        return this.spcAssortment;
    }
    
    public void setSpcAssortment(boolean spcAssortment) {
        this.spcAssortment = spcAssortment;
    }
    public boolean isCustomerLevelPp() {
        return this.customerLevelPp;
    }
    
    public void setCustomerLevelPp(boolean customerLevelPp) {
        this.customerLevelPp = customerLevelPp;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public Date getCreDate() {
        return this.creDate;
    }
    
    public void setCreDate(Date creDate) {
        this.creDate = creDate;
    }
    public String getCreId() {
        return this.creId;
    }
    
    public void setCreId(String creId) {
        this.creId = creId;
    }
    public Date getModDate() {
        return this.modDate;
    }
    
    public void setModDate(Date modDate) {
        this.modDate = modDate;
    }
    public String getModId() {
        return this.modId;
    }
    
    public void setModId(String modId) {
        this.modId = modId;
    }
    public Date getApprovalDate() {
        return this.approvalDate;
    }
    
    public void setApprovalDate(Date approvalDate) {
        this.approvalDate = approvalDate;
    }
    public String getApprovalId() {
        return this.approvalId;
    }
    
    public void setApprovalId(String approvalId) {
        this.approvalId = approvalId;
    }
    public boolean isExclusivityInd() {
        return this.exclusivityInd;
    }
    
    public void setExclusivityInd(boolean exclusivityInd) {
        this.exclusivityInd = exclusivityInd;
    }
    public String getPrevStatus() {
        return this.prevStatus;
    }
    
    public void setPrevStatus(String prevStatus) {
        this.prevStatus = prevStatus;
    }
    public Date getCancelDate() {
        return this.cancelDate;
    }
    
    public void setCancelDate(Date cancelDate) {
        this.cancelDate = cancelDate;
    }
    public String getCancelId() {
        return this.cancelId;
    }
    
    public void setCancelId(String cancelId) {
        this.cancelId = cancelId;
    }
    public String getExContractId() {
        return this.exContractId;
    }
    
    public void setExContractId(String exContractId) {
        this.exContractId = exContractId;
    }
    public boolean isInvoiceWithoutVat() {
        return this.invoiceWithoutVat;
    }
    
    public void setInvoiceWithoutVat(boolean invoiceWithoutVat) {
        this.invoiceWithoutVat = invoiceWithoutVat;
    }
    public Set getCustomerContracts() {
        return this.customerContracts;
    }
    
    public void setCustomerContracts(Set customerContracts) {
        this.customerContracts = customerContracts;
    }
    public ContractPricingPriority getContractPricingPriority() {
        return this.contractPricingPriority;
    }
    
    public void setContractPricingPriority(ContractPricingPriority contractPricingPriority) {
        this.contractPricingPriority = contractPricingPriority;
    }

    @Override
    public String toString() {
        return "CustomerContract{" + "contract=" + contract + ", customerContract=" + customerContract + ", customerMaster=" + customerMaster + ", description=" + description + ", status=" + status + '}';
    }

}


