package com.weigandtconsulting.javaschool.db.hibernate.entity;
// Generated Oct 28, 2015 4:51:35 PM by Hibernate Tools 4.3.1



/**
 * DeliveryPointId generated by hbm2java
 */
public class DeliveryPointId  implements java.io.Serializable {


     private short deliveryPoint;
     private long customerId;

    public DeliveryPointId() {
    }

    public DeliveryPointId(short deliveryPoint, long customerId) {
       this.deliveryPoint = deliveryPoint;
       this.customerId = customerId;
    }
   
    public short getDeliveryPoint() {
        return this.deliveryPoint;
    }
    
    public void setDeliveryPoint(short deliveryPoint) {
        this.deliveryPoint = deliveryPoint;
    }
    public long getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(long customerId) {
        this.customerId = customerId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DeliveryPointId) ) return false;
		 DeliveryPointId castOther = ( DeliveryPointId ) other; 
         
		 return (this.getDeliveryPoint()==castOther.getDeliveryPoint())
 && (this.getCustomerId()==castOther.getCustomerId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getDeliveryPoint();
         result = 37 * result + (int) this.getCustomerId();
         return result;
   }   


}


