package com.weigandtconsulting.javaschool.db.hibernate.entity;
// Generated Oct 28, 2015 4:51:35 PM by Hibernate Tools 4.3.1



/**
 * ViewLookupDeliveryPoint generated by hbm2java
 */
public class ViewLookupDeliveryPoint  implements java.io.Serializable {


     private ViewLookupDeliveryPointId id;

    public ViewLookupDeliveryPoint() {
    }

    public ViewLookupDeliveryPoint(ViewLookupDeliveryPointId id) {
       this.id = id;
    }
   
    public ViewLookupDeliveryPointId getId() {
        return this.id;
    }
    
    public void setId(ViewLookupDeliveryPointId id) {
        this.id = id;
    }




}


