package com.weigandtconsulting.javaschool.db.hibernate.entity;
// Generated Oct 28, 2015 4:51:35 PM by Hibernate Tools 4.3.1



/**
 * ViewcSearchDocuments generated by hbm2java
 */
public class ViewcSearchDocuments  implements java.io.Serializable {


     private ViewcSearchDocumentsId id;

    public ViewcSearchDocuments() {
    }

    public ViewcSearchDocuments(ViewcSearchDocumentsId id) {
       this.id = id;
    }
   
    public ViewcSearchDocumentsId getId() {
        return this.id;
    }
    
    public void setId(ViewcSearchDocumentsId id) {
        this.id = id;
    }




}


