package com.weigandtconsulting.javaschool.db.hibernate.entity;
// Generated Oct 28, 2015 4:51:35 PM by Hibernate Tools 4.3.1



/**
 * ViewLookupItem generated by hbm2java
 */
public class ViewLookupItem  implements java.io.Serializable {


     private ViewLookupItemId id;

    public ViewLookupItem() {
    }

    public ViewLookupItem(ViewLookupItemId id) {
       this.id = id;
    }
   
    public ViewLookupItemId getId() {
        return this.id;
    }
    
    public void setId(ViewLookupItemId id) {
        this.id = id;
    }




}


