package com.weigandtconsulting.javaschool.db.hibernate.entity;
// Generated Oct 28, 2015 4:51:35 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * ViewLookupItemId generated by hbm2java
 */
public class ViewLookupItemId  implements java.io.Serializable {


     private String id;
     private String description;
     private String idLookup;
     private String descriptionLookup;
     private String lookup;
     private long supplierId;
     private String suppDescription;
     private String supplierIdLookup;
     private String suppDescriptionLookup;
     private short categoryId;
     private short subcategoryId;
     private short groupId;
     private String categoryIdLookup;
     private String subcategoryIdLookup;
     private String groupIdLookup;
     private long locationId;
     private String locationType;
     private BigDecimal availableQty;
     private BigDecimal stockOnHand;
     private String uom;
     private short dept;
     private short groupNo;
     private String sellableInd;
     private String packInd;
     private String itemType;
     private String containerItem;
     private BigDecimal retailPrice;
     private short sector;
     private String sectorLookup;
     private String emballageInd;

    public ViewLookupItemId() {
    }

	
    public ViewLookupItemId(String id, String description, String idLookup, String descriptionLookup, long supplierId, String suppDescription, String suppDescriptionLookup, short categoryId, short subcategoryId, short groupId, long locationId, String locationType, BigDecimal stockOnHand, String uom, short dept, short groupNo, String sellableInd, String packInd, short sector) {
        this.id = id;
        this.description = description;
        this.idLookup = idLookup;
        this.descriptionLookup = descriptionLookup;
        this.supplierId = supplierId;
        this.suppDescription = suppDescription;
        this.suppDescriptionLookup = suppDescriptionLookup;
        this.categoryId = categoryId;
        this.subcategoryId = subcategoryId;
        this.groupId = groupId;
        this.locationId = locationId;
        this.locationType = locationType;
        this.stockOnHand = stockOnHand;
        this.uom = uom;
        this.dept = dept;
        this.groupNo = groupNo;
        this.sellableInd = sellableInd;
        this.packInd = packInd;
        this.sector = sector;
    }
    public ViewLookupItemId(String id, String description, String idLookup, String descriptionLookup, String lookup, long supplierId, String suppDescription, String supplierIdLookup, String suppDescriptionLookup, short categoryId, short subcategoryId, short groupId, String categoryIdLookup, String subcategoryIdLookup, String groupIdLookup, long locationId, String locationType, BigDecimal availableQty, BigDecimal stockOnHand, String uom, short dept, short groupNo, String sellableInd, String packInd, String itemType, String containerItem, BigDecimal retailPrice, short sector, String sectorLookup, String emballageInd) {
       this.id = id;
       this.description = description;
       this.idLookup = idLookup;
       this.descriptionLookup = descriptionLookup;
       this.lookup = lookup;
       this.supplierId = supplierId;
       this.suppDescription = suppDescription;
       this.supplierIdLookup = supplierIdLookup;
       this.suppDescriptionLookup = suppDescriptionLookup;
       this.categoryId = categoryId;
       this.subcategoryId = subcategoryId;
       this.groupId = groupId;
       this.categoryIdLookup = categoryIdLookup;
       this.subcategoryIdLookup = subcategoryIdLookup;
       this.groupIdLookup = groupIdLookup;
       this.locationId = locationId;
       this.locationType = locationType;
       this.availableQty = availableQty;
       this.stockOnHand = stockOnHand;
       this.uom = uom;
       this.dept = dept;
       this.groupNo = groupNo;
       this.sellableInd = sellableInd;
       this.packInd = packInd;
       this.itemType = itemType;
       this.containerItem = containerItem;
       this.retailPrice = retailPrice;
       this.sector = sector;
       this.sectorLookup = sectorLookup;
       this.emballageInd = emballageInd;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getIdLookup() {
        return this.idLookup;
    }
    
    public void setIdLookup(String idLookup) {
        this.idLookup = idLookup;
    }
    public String getDescriptionLookup() {
        return this.descriptionLookup;
    }
    
    public void setDescriptionLookup(String descriptionLookup) {
        this.descriptionLookup = descriptionLookup;
    }
    public String getLookup() {
        return this.lookup;
    }
    
    public void setLookup(String lookup) {
        this.lookup = lookup;
    }
    public long getSupplierId() {
        return this.supplierId;
    }
    
    public void setSupplierId(long supplierId) {
        this.supplierId = supplierId;
    }
    public String getSuppDescription() {
        return this.suppDescription;
    }
    
    public void setSuppDescription(String suppDescription) {
        this.suppDescription = suppDescription;
    }
    public String getSupplierIdLookup() {
        return this.supplierIdLookup;
    }
    
    public void setSupplierIdLookup(String supplierIdLookup) {
        this.supplierIdLookup = supplierIdLookup;
    }
    public String getSuppDescriptionLookup() {
        return this.suppDescriptionLookup;
    }
    
    public void setSuppDescriptionLookup(String suppDescriptionLookup) {
        this.suppDescriptionLookup = suppDescriptionLookup;
    }
    public short getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(short categoryId) {
        this.categoryId = categoryId;
    }
    public short getSubcategoryId() {
        return this.subcategoryId;
    }
    
    public void setSubcategoryId(short subcategoryId) {
        this.subcategoryId = subcategoryId;
    }
    public short getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(short groupId) {
        this.groupId = groupId;
    }
    public String getCategoryIdLookup() {
        return this.categoryIdLookup;
    }
    
    public void setCategoryIdLookup(String categoryIdLookup) {
        this.categoryIdLookup = categoryIdLookup;
    }
    public String getSubcategoryIdLookup() {
        return this.subcategoryIdLookup;
    }
    
    public void setSubcategoryIdLookup(String subcategoryIdLookup) {
        this.subcategoryIdLookup = subcategoryIdLookup;
    }
    public String getGroupIdLookup() {
        return this.groupIdLookup;
    }
    
    public void setGroupIdLookup(String groupIdLookup) {
        this.groupIdLookup = groupIdLookup;
    }
    public long getLocationId() {
        return this.locationId;
    }
    
    public void setLocationId(long locationId) {
        this.locationId = locationId;
    }
    public String getLocationType() {
        return this.locationType;
    }
    
    public void setLocationType(String locationType) {
        this.locationType = locationType;
    }
    public BigDecimal getAvailableQty() {
        return this.availableQty;
    }
    
    public void setAvailableQty(BigDecimal availableQty) {
        this.availableQty = availableQty;
    }
    public BigDecimal getStockOnHand() {
        return this.stockOnHand;
    }
    
    public void setStockOnHand(BigDecimal stockOnHand) {
        this.stockOnHand = stockOnHand;
    }
    public String getUom() {
        return this.uom;
    }
    
    public void setUom(String uom) {
        this.uom = uom;
    }
    public short getDept() {
        return this.dept;
    }
    
    public void setDept(short dept) {
        this.dept = dept;
    }
    public short getGroupNo() {
        return this.groupNo;
    }
    
    public void setGroupNo(short groupNo) {
        this.groupNo = groupNo;
    }
    public String getSellableInd() {
        return this.sellableInd;
    }
    
    public void setSellableInd(String sellableInd) {
        this.sellableInd = sellableInd;
    }
    public String getPackInd() {
        return this.packInd;
    }
    
    public void setPackInd(String packInd) {
        this.packInd = packInd;
    }
    public String getItemType() {
        return this.itemType;
    }
    
    public void setItemType(String itemType) {
        this.itemType = itemType;
    }
    public String getContainerItem() {
        return this.containerItem;
    }
    
    public void setContainerItem(String containerItem) {
        this.containerItem = containerItem;
    }
    public BigDecimal getRetailPrice() {
        return this.retailPrice;
    }
    
    public void setRetailPrice(BigDecimal retailPrice) {
        this.retailPrice = retailPrice;
    }
    public short getSector() {
        return this.sector;
    }
    
    public void setSector(short sector) {
        this.sector = sector;
    }
    public String getSectorLookup() {
        return this.sectorLookup;
    }
    
    public void setSectorLookup(String sectorLookup) {
        this.sectorLookup = sectorLookup;
    }
    public String getEmballageInd() {
        return this.emballageInd;
    }
    
    public void setEmballageInd(String emballageInd) {
        this.emballageInd = emballageInd;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ViewLookupItemId) ) return false;
		 ViewLookupItemId castOther = ( ViewLookupItemId ) other; 
         
		 return ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) )
 && ( (this.getDescription()==castOther.getDescription()) || ( this.getDescription()!=null && castOther.getDescription()!=null && this.getDescription().equals(castOther.getDescription()) ) )
 && ( (this.getIdLookup()==castOther.getIdLookup()) || ( this.getIdLookup()!=null && castOther.getIdLookup()!=null && this.getIdLookup().equals(castOther.getIdLookup()) ) )
 && ( (this.getDescriptionLookup()==castOther.getDescriptionLookup()) || ( this.getDescriptionLookup()!=null && castOther.getDescriptionLookup()!=null && this.getDescriptionLookup().equals(castOther.getDescriptionLookup()) ) )
 && ( (this.getLookup()==castOther.getLookup()) || ( this.getLookup()!=null && castOther.getLookup()!=null && this.getLookup().equals(castOther.getLookup()) ) )
 && (this.getSupplierId()==castOther.getSupplierId())
 && ( (this.getSuppDescription()==castOther.getSuppDescription()) || ( this.getSuppDescription()!=null && castOther.getSuppDescription()!=null && this.getSuppDescription().equals(castOther.getSuppDescription()) ) )
 && ( (this.getSupplierIdLookup()==castOther.getSupplierIdLookup()) || ( this.getSupplierIdLookup()!=null && castOther.getSupplierIdLookup()!=null && this.getSupplierIdLookup().equals(castOther.getSupplierIdLookup()) ) )
 && ( (this.getSuppDescriptionLookup()==castOther.getSuppDescriptionLookup()) || ( this.getSuppDescriptionLookup()!=null && castOther.getSuppDescriptionLookup()!=null && this.getSuppDescriptionLookup().equals(castOther.getSuppDescriptionLookup()) ) )
 && (this.getCategoryId()==castOther.getCategoryId())
 && (this.getSubcategoryId()==castOther.getSubcategoryId())
 && (this.getGroupId()==castOther.getGroupId())
 && ( (this.getCategoryIdLookup()==castOther.getCategoryIdLookup()) || ( this.getCategoryIdLookup()!=null && castOther.getCategoryIdLookup()!=null && this.getCategoryIdLookup().equals(castOther.getCategoryIdLookup()) ) )
 && ( (this.getSubcategoryIdLookup()==castOther.getSubcategoryIdLookup()) || ( this.getSubcategoryIdLookup()!=null && castOther.getSubcategoryIdLookup()!=null && this.getSubcategoryIdLookup().equals(castOther.getSubcategoryIdLookup()) ) )
 && ( (this.getGroupIdLookup()==castOther.getGroupIdLookup()) || ( this.getGroupIdLookup()!=null && castOther.getGroupIdLookup()!=null && this.getGroupIdLookup().equals(castOther.getGroupIdLookup()) ) )
 && (this.getLocationId()==castOther.getLocationId())
 && ( (this.getLocationType()==castOther.getLocationType()) || ( this.getLocationType()!=null && castOther.getLocationType()!=null && this.getLocationType().equals(castOther.getLocationType()) ) )
 && ( (this.getAvailableQty()==castOther.getAvailableQty()) || ( this.getAvailableQty()!=null && castOther.getAvailableQty()!=null && this.getAvailableQty().equals(castOther.getAvailableQty()) ) )
 && ( (this.getStockOnHand()==castOther.getStockOnHand()) || ( this.getStockOnHand()!=null && castOther.getStockOnHand()!=null && this.getStockOnHand().equals(castOther.getStockOnHand()) ) )
 && ( (this.getUom()==castOther.getUom()) || ( this.getUom()!=null && castOther.getUom()!=null && this.getUom().equals(castOther.getUom()) ) )
 && (this.getDept()==castOther.getDept())
 && (this.getGroupNo()==castOther.getGroupNo())
 && ( (this.getSellableInd()==castOther.getSellableInd()) || ( this.getSellableInd()!=null && castOther.getSellableInd()!=null && this.getSellableInd().equals(castOther.getSellableInd()) ) )
 && ( (this.getPackInd()==castOther.getPackInd()) || ( this.getPackInd()!=null && castOther.getPackInd()!=null && this.getPackInd().equals(castOther.getPackInd()) ) )
 && ( (this.getItemType()==castOther.getItemType()) || ( this.getItemType()!=null && castOther.getItemType()!=null && this.getItemType().equals(castOther.getItemType()) ) )
 && ( (this.getContainerItem()==castOther.getContainerItem()) || ( this.getContainerItem()!=null && castOther.getContainerItem()!=null && this.getContainerItem().equals(castOther.getContainerItem()) ) )
 && ( (this.getRetailPrice()==castOther.getRetailPrice()) || ( this.getRetailPrice()!=null && castOther.getRetailPrice()!=null && this.getRetailPrice().equals(castOther.getRetailPrice()) ) )
 && (this.getSector()==castOther.getSector())
 && ( (this.getSectorLookup()==castOther.getSectorLookup()) || ( this.getSectorLookup()!=null && castOther.getSectorLookup()!=null && this.getSectorLookup().equals(castOther.getSectorLookup()) ) )
 && ( (this.getEmballageInd()==castOther.getEmballageInd()) || ( this.getEmballageInd()!=null && castOther.getEmballageInd()!=null && this.getEmballageInd().equals(castOther.getEmballageInd()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
         result = 37 * result + ( getDescription() == null ? 0 : this.getDescription().hashCode() );
         result = 37 * result + ( getIdLookup() == null ? 0 : this.getIdLookup().hashCode() );
         result = 37 * result + ( getDescriptionLookup() == null ? 0 : this.getDescriptionLookup().hashCode() );
         result = 37 * result + ( getLookup() == null ? 0 : this.getLookup().hashCode() );
         result = 37 * result + (int) this.getSupplierId();
         result = 37 * result + ( getSuppDescription() == null ? 0 : this.getSuppDescription().hashCode() );
         result = 37 * result + ( getSupplierIdLookup() == null ? 0 : this.getSupplierIdLookup().hashCode() );
         result = 37 * result + ( getSuppDescriptionLookup() == null ? 0 : this.getSuppDescriptionLookup().hashCode() );
         result = 37 * result + this.getCategoryId();
         result = 37 * result + this.getSubcategoryId();
         result = 37 * result + this.getGroupId();
         result = 37 * result + ( getCategoryIdLookup() == null ? 0 : this.getCategoryIdLookup().hashCode() );
         result = 37 * result + ( getSubcategoryIdLookup() == null ? 0 : this.getSubcategoryIdLookup().hashCode() );
         result = 37 * result + ( getGroupIdLookup() == null ? 0 : this.getGroupIdLookup().hashCode() );
         result = 37 * result + (int) this.getLocationId();
         result = 37 * result + ( getLocationType() == null ? 0 : this.getLocationType().hashCode() );
         result = 37 * result + ( getAvailableQty() == null ? 0 : this.getAvailableQty().hashCode() );
         result = 37 * result + ( getStockOnHand() == null ? 0 : this.getStockOnHand().hashCode() );
         result = 37 * result + ( getUom() == null ? 0 : this.getUom().hashCode() );
         result = 37 * result + this.getDept();
         result = 37 * result + this.getGroupNo();
         result = 37 * result + ( getSellableInd() == null ? 0 : this.getSellableInd().hashCode() );
         result = 37 * result + ( getPackInd() == null ? 0 : this.getPackInd().hashCode() );
         result = 37 * result + ( getItemType() == null ? 0 : this.getItemType().hashCode() );
         result = 37 * result + ( getContainerItem() == null ? 0 : this.getContainerItem().hashCode() );
         result = 37 * result + ( getRetailPrice() == null ? 0 : this.getRetailPrice().hashCode() );
         result = 37 * result + this.getSector();
         result = 37 * result + ( getSectorLookup() == null ? 0 : this.getSectorLookup().hashCode() );
         result = 37 * result + ( getEmballageInd() == null ? 0 : this.getEmballageInd().hashCode() );
         return result;
   }   


}


