package com.weigandtconsulting.javaschool.db.hibernate.entity;
// Generated Oct 28, 2015 4:51:35 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * ViewcSearchDocumentsId generated by hbm2java
 */
public class ViewcSearchDocumentsId  implements java.io.Serializable {


     private BigDecimal documentId;
     private String documentType;
     private String documentTypeLookup;
     private String documentSubtype;
     private String documentNum;
     private String documentNumSort;
     private Date documentDate;
     private String channelLookup;
     private String customerLookup;
     private String status;
     private String statusLookup;
     private BigDecimal locationId;
     private String locationType;
     private BigDecimal customerId;
     private String locationLookup;
     private Short deliveryPointId;
     private String deliveryPointLookup;
     private BigDecimal fiscalised;
     private String issuedBy;
     private String sourceLookup;
     private String createdBy;
     private BigDecimal stornoInd;
     private String source;
     private BigDecimal consInd;
     private BigDecimal orderId;
     private BigDecimal returnId;
     private Long orderTsfNo;
     private Long returnTsfNo;
     private BigDecimal refDocumentId;
     private String fullUserName;
     private BigDecimal amtTotal;
     private String refDocumentNum;

    public ViewcSearchDocumentsId() {
    }

    public ViewcSearchDocumentsId(BigDecimal documentId, String documentType, String documentTypeLookup, String documentSubtype, String documentNum, String documentNumSort, Date documentDate, String channelLookup, String customerLookup, String status, String statusLookup, BigDecimal locationId, String locationType, BigDecimal customerId, String locationLookup, Short deliveryPointId, String deliveryPointLookup, BigDecimal fiscalised, String issuedBy, String sourceLookup, String createdBy, BigDecimal stornoInd, String source, BigDecimal consInd, BigDecimal orderId, BigDecimal returnId, Long orderTsfNo, Long returnTsfNo, BigDecimal refDocumentId, String fullUserName, BigDecimal amtTotal, String refDocumentNum) {
       this.documentId = documentId;
       this.documentType = documentType;
       this.documentTypeLookup = documentTypeLookup;
       this.documentSubtype = documentSubtype;
       this.documentNum = documentNum;
       this.documentNumSort = documentNumSort;
       this.documentDate = documentDate;
       this.channelLookup = channelLookup;
       this.customerLookup = customerLookup;
       this.status = status;
       this.statusLookup = statusLookup;
       this.locationId = locationId;
       this.locationType = locationType;
       this.customerId = customerId;
       this.locationLookup = locationLookup;
       this.deliveryPointId = deliveryPointId;
       this.deliveryPointLookup = deliveryPointLookup;
       this.fiscalised = fiscalised;
       this.issuedBy = issuedBy;
       this.sourceLookup = sourceLookup;
       this.createdBy = createdBy;
       this.stornoInd = stornoInd;
       this.source = source;
       this.consInd = consInd;
       this.orderId = orderId;
       this.returnId = returnId;
       this.orderTsfNo = orderTsfNo;
       this.returnTsfNo = returnTsfNo;
       this.refDocumentId = refDocumentId;
       this.fullUserName = fullUserName;
       this.amtTotal = amtTotal;
       this.refDocumentNum = refDocumentNum;
    }
   
    public BigDecimal getDocumentId() {
        return this.documentId;
    }
    
    public void setDocumentId(BigDecimal documentId) {
        this.documentId = documentId;
    }
    public String getDocumentType() {
        return this.documentType;
    }
    
    public void setDocumentType(String documentType) {
        this.documentType = documentType;
    }
    public String getDocumentTypeLookup() {
        return this.documentTypeLookup;
    }
    
    public void setDocumentTypeLookup(String documentTypeLookup) {
        this.documentTypeLookup = documentTypeLookup;
    }
    public String getDocumentSubtype() {
        return this.documentSubtype;
    }
    
    public void setDocumentSubtype(String documentSubtype) {
        this.documentSubtype = documentSubtype;
    }
    public String getDocumentNum() {
        return this.documentNum;
    }
    
    public void setDocumentNum(String documentNum) {
        this.documentNum = documentNum;
    }
    public String getDocumentNumSort() {
        return this.documentNumSort;
    }
    
    public void setDocumentNumSort(String documentNumSort) {
        this.documentNumSort = documentNumSort;
    }
    public Date getDocumentDate() {
        return this.documentDate;
    }
    
    public void setDocumentDate(Date documentDate) {
        this.documentDate = documentDate;
    }
    public String getChannelLookup() {
        return this.channelLookup;
    }
    
    public void setChannelLookup(String channelLookup) {
        this.channelLookup = channelLookup;
    }
    public String getCustomerLookup() {
        return this.customerLookup;
    }
    
    public void setCustomerLookup(String customerLookup) {
        this.customerLookup = customerLookup;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getStatusLookup() {
        return this.statusLookup;
    }
    
    public void setStatusLookup(String statusLookup) {
        this.statusLookup = statusLookup;
    }
    public BigDecimal getLocationId() {
        return this.locationId;
    }
    
    public void setLocationId(BigDecimal locationId) {
        this.locationId = locationId;
    }
    public String getLocationType() {
        return this.locationType;
    }
    
    public void setLocationType(String locationType) {
        this.locationType = locationType;
    }
    public BigDecimal getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(BigDecimal customerId) {
        this.customerId = customerId;
    }
    public String getLocationLookup() {
        return this.locationLookup;
    }
    
    public void setLocationLookup(String locationLookup) {
        this.locationLookup = locationLookup;
    }
    public Short getDeliveryPointId() {
        return this.deliveryPointId;
    }
    
    public void setDeliveryPointId(Short deliveryPointId) {
        this.deliveryPointId = deliveryPointId;
    }
    public String getDeliveryPointLookup() {
        return this.deliveryPointLookup;
    }
    
    public void setDeliveryPointLookup(String deliveryPointLookup) {
        this.deliveryPointLookup = deliveryPointLookup;
    }
    public BigDecimal getFiscalised() {
        return this.fiscalised;
    }
    
    public void setFiscalised(BigDecimal fiscalised) {
        this.fiscalised = fiscalised;
    }
    public String getIssuedBy() {
        return this.issuedBy;
    }
    
    public void setIssuedBy(String issuedBy) {
        this.issuedBy = issuedBy;
    }
    public String getSourceLookup() {
        return this.sourceLookup;
    }
    
    public void setSourceLookup(String sourceLookup) {
        this.sourceLookup = sourceLookup;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public BigDecimal getStornoInd() {
        return this.stornoInd;
    }
    
    public void setStornoInd(BigDecimal stornoInd) {
        this.stornoInd = stornoInd;
    }
    public String getSource() {
        return this.source;
    }
    
    public void setSource(String source) {
        this.source = source;
    }
    public BigDecimal getConsInd() {
        return this.consInd;
    }
    
    public void setConsInd(BigDecimal consInd) {
        this.consInd = consInd;
    }
    public BigDecimal getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(BigDecimal orderId) {
        this.orderId = orderId;
    }
    public BigDecimal getReturnId() {
        return this.returnId;
    }
    
    public void setReturnId(BigDecimal returnId) {
        this.returnId = returnId;
    }
    public Long getOrderTsfNo() {
        return this.orderTsfNo;
    }
    
    public void setOrderTsfNo(Long orderTsfNo) {
        this.orderTsfNo = orderTsfNo;
    }
    public Long getReturnTsfNo() {
        return this.returnTsfNo;
    }
    
    public void setReturnTsfNo(Long returnTsfNo) {
        this.returnTsfNo = returnTsfNo;
    }
    public BigDecimal getRefDocumentId() {
        return this.refDocumentId;
    }
    
    public void setRefDocumentId(BigDecimal refDocumentId) {
        this.refDocumentId = refDocumentId;
    }
    public String getFullUserName() {
        return this.fullUserName;
    }
    
    public void setFullUserName(String fullUserName) {
        this.fullUserName = fullUserName;
    }
    public BigDecimal getAmtTotal() {
        return this.amtTotal;
    }
    
    public void setAmtTotal(BigDecimal amtTotal) {
        this.amtTotal = amtTotal;
    }
    public String getRefDocumentNum() {
        return this.refDocumentNum;
    }
    
    public void setRefDocumentNum(String refDocumentNum) {
        this.refDocumentNum = refDocumentNum;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ViewcSearchDocumentsId) ) return false;
		 ViewcSearchDocumentsId castOther = ( ViewcSearchDocumentsId ) other; 
         
		 return ( (this.getDocumentId()==castOther.getDocumentId()) || ( this.getDocumentId()!=null && castOther.getDocumentId()!=null && this.getDocumentId().equals(castOther.getDocumentId()) ) )
 && ( (this.getDocumentType()==castOther.getDocumentType()) || ( this.getDocumentType()!=null && castOther.getDocumentType()!=null && this.getDocumentType().equals(castOther.getDocumentType()) ) )
 && ( (this.getDocumentTypeLookup()==castOther.getDocumentTypeLookup()) || ( this.getDocumentTypeLookup()!=null && castOther.getDocumentTypeLookup()!=null && this.getDocumentTypeLookup().equals(castOther.getDocumentTypeLookup()) ) )
 && ( (this.getDocumentSubtype()==castOther.getDocumentSubtype()) || ( this.getDocumentSubtype()!=null && castOther.getDocumentSubtype()!=null && this.getDocumentSubtype().equals(castOther.getDocumentSubtype()) ) )
 && ( (this.getDocumentNum()==castOther.getDocumentNum()) || ( this.getDocumentNum()!=null && castOther.getDocumentNum()!=null && this.getDocumentNum().equals(castOther.getDocumentNum()) ) )
 && ( (this.getDocumentNumSort()==castOther.getDocumentNumSort()) || ( this.getDocumentNumSort()!=null && castOther.getDocumentNumSort()!=null && this.getDocumentNumSort().equals(castOther.getDocumentNumSort()) ) )
 && ( (this.getDocumentDate()==castOther.getDocumentDate()) || ( this.getDocumentDate()!=null && castOther.getDocumentDate()!=null && this.getDocumentDate().equals(castOther.getDocumentDate()) ) )
 && ( (this.getChannelLookup()==castOther.getChannelLookup()) || ( this.getChannelLookup()!=null && castOther.getChannelLookup()!=null && this.getChannelLookup().equals(castOther.getChannelLookup()) ) )
 && ( (this.getCustomerLookup()==castOther.getCustomerLookup()) || ( this.getCustomerLookup()!=null && castOther.getCustomerLookup()!=null && this.getCustomerLookup().equals(castOther.getCustomerLookup()) ) )
 && ( (this.getStatus()==castOther.getStatus()) || ( this.getStatus()!=null && castOther.getStatus()!=null && this.getStatus().equals(castOther.getStatus()) ) )
 && ( (this.getStatusLookup()==castOther.getStatusLookup()) || ( this.getStatusLookup()!=null && castOther.getStatusLookup()!=null && this.getStatusLookup().equals(castOther.getStatusLookup()) ) )
 && ( (this.getLocationId()==castOther.getLocationId()) || ( this.getLocationId()!=null && castOther.getLocationId()!=null && this.getLocationId().equals(castOther.getLocationId()) ) )
 && ( (this.getLocationType()==castOther.getLocationType()) || ( this.getLocationType()!=null && castOther.getLocationType()!=null && this.getLocationType().equals(castOther.getLocationType()) ) )
 && ( (this.getCustomerId()==castOther.getCustomerId()) || ( this.getCustomerId()!=null && castOther.getCustomerId()!=null && this.getCustomerId().equals(castOther.getCustomerId()) ) )
 && ( (this.getLocationLookup()==castOther.getLocationLookup()) || ( this.getLocationLookup()!=null && castOther.getLocationLookup()!=null && this.getLocationLookup().equals(castOther.getLocationLookup()) ) )
 && ( (this.getDeliveryPointId()==castOther.getDeliveryPointId()) || ( this.getDeliveryPointId()!=null && castOther.getDeliveryPointId()!=null && this.getDeliveryPointId().equals(castOther.getDeliveryPointId()) ) )
 && ( (this.getDeliveryPointLookup()==castOther.getDeliveryPointLookup()) || ( this.getDeliveryPointLookup()!=null && castOther.getDeliveryPointLookup()!=null && this.getDeliveryPointLookup().equals(castOther.getDeliveryPointLookup()) ) )
 && ( (this.getFiscalised()==castOther.getFiscalised()) || ( this.getFiscalised()!=null && castOther.getFiscalised()!=null && this.getFiscalised().equals(castOther.getFiscalised()) ) )
 && ( (this.getIssuedBy()==castOther.getIssuedBy()) || ( this.getIssuedBy()!=null && castOther.getIssuedBy()!=null && this.getIssuedBy().equals(castOther.getIssuedBy()) ) )
 && ( (this.getSourceLookup()==castOther.getSourceLookup()) || ( this.getSourceLookup()!=null && castOther.getSourceLookup()!=null && this.getSourceLookup().equals(castOther.getSourceLookup()) ) )
 && ( (this.getCreatedBy()==castOther.getCreatedBy()) || ( this.getCreatedBy()!=null && castOther.getCreatedBy()!=null && this.getCreatedBy().equals(castOther.getCreatedBy()) ) )
 && ( (this.getStornoInd()==castOther.getStornoInd()) || ( this.getStornoInd()!=null && castOther.getStornoInd()!=null && this.getStornoInd().equals(castOther.getStornoInd()) ) )
 && ( (this.getSource()==castOther.getSource()) || ( this.getSource()!=null && castOther.getSource()!=null && this.getSource().equals(castOther.getSource()) ) )
 && ( (this.getConsInd()==castOther.getConsInd()) || ( this.getConsInd()!=null && castOther.getConsInd()!=null && this.getConsInd().equals(castOther.getConsInd()) ) )
 && ( (this.getOrderId()==castOther.getOrderId()) || ( this.getOrderId()!=null && castOther.getOrderId()!=null && this.getOrderId().equals(castOther.getOrderId()) ) )
 && ( (this.getReturnId()==castOther.getReturnId()) || ( this.getReturnId()!=null && castOther.getReturnId()!=null && this.getReturnId().equals(castOther.getReturnId()) ) )
 && ( (this.getOrderTsfNo()==castOther.getOrderTsfNo()) || ( this.getOrderTsfNo()!=null && castOther.getOrderTsfNo()!=null && this.getOrderTsfNo().equals(castOther.getOrderTsfNo()) ) )
 && ( (this.getReturnTsfNo()==castOther.getReturnTsfNo()) || ( this.getReturnTsfNo()!=null && castOther.getReturnTsfNo()!=null && this.getReturnTsfNo().equals(castOther.getReturnTsfNo()) ) )
 && ( (this.getRefDocumentId()==castOther.getRefDocumentId()) || ( this.getRefDocumentId()!=null && castOther.getRefDocumentId()!=null && this.getRefDocumentId().equals(castOther.getRefDocumentId()) ) )
 && ( (this.getFullUserName()==castOther.getFullUserName()) || ( this.getFullUserName()!=null && castOther.getFullUserName()!=null && this.getFullUserName().equals(castOther.getFullUserName()) ) )
 && ( (this.getAmtTotal()==castOther.getAmtTotal()) || ( this.getAmtTotal()!=null && castOther.getAmtTotal()!=null && this.getAmtTotal().equals(castOther.getAmtTotal()) ) )
 && ( (this.getRefDocumentNum()==castOther.getRefDocumentNum()) || ( this.getRefDocumentNum()!=null && castOther.getRefDocumentNum()!=null && this.getRefDocumentNum().equals(castOther.getRefDocumentNum()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDocumentId() == null ? 0 : this.getDocumentId().hashCode() );
         result = 37 * result + ( getDocumentType() == null ? 0 : this.getDocumentType().hashCode() );
         result = 37 * result + ( getDocumentTypeLookup() == null ? 0 : this.getDocumentTypeLookup().hashCode() );
         result = 37 * result + ( getDocumentSubtype() == null ? 0 : this.getDocumentSubtype().hashCode() );
         result = 37 * result + ( getDocumentNum() == null ? 0 : this.getDocumentNum().hashCode() );
         result = 37 * result + ( getDocumentNumSort() == null ? 0 : this.getDocumentNumSort().hashCode() );
         result = 37 * result + ( getDocumentDate() == null ? 0 : this.getDocumentDate().hashCode() );
         result = 37 * result + ( getChannelLookup() == null ? 0 : this.getChannelLookup().hashCode() );
         result = 37 * result + ( getCustomerLookup() == null ? 0 : this.getCustomerLookup().hashCode() );
         result = 37 * result + ( getStatus() == null ? 0 : this.getStatus().hashCode() );
         result = 37 * result + ( getStatusLookup() == null ? 0 : this.getStatusLookup().hashCode() );
         result = 37 * result + ( getLocationId() == null ? 0 : this.getLocationId().hashCode() );
         result = 37 * result + ( getLocationType() == null ? 0 : this.getLocationType().hashCode() );
         result = 37 * result + ( getCustomerId() == null ? 0 : this.getCustomerId().hashCode() );
         result = 37 * result + ( getLocationLookup() == null ? 0 : this.getLocationLookup().hashCode() );
         result = 37 * result + ( getDeliveryPointId() == null ? 0 : this.getDeliveryPointId().hashCode() );
         result = 37 * result + ( getDeliveryPointLookup() == null ? 0 : this.getDeliveryPointLookup().hashCode() );
         result = 37 * result + ( getFiscalised() == null ? 0 : this.getFiscalised().hashCode() );
         result = 37 * result + ( getIssuedBy() == null ? 0 : this.getIssuedBy().hashCode() );
         result = 37 * result + ( getSourceLookup() == null ? 0 : this.getSourceLookup().hashCode() );
         result = 37 * result + ( getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode() );
         result = 37 * result + ( getStornoInd() == null ? 0 : this.getStornoInd().hashCode() );
         result = 37 * result + ( getSource() == null ? 0 : this.getSource().hashCode() );
         result = 37 * result + ( getConsInd() == null ? 0 : this.getConsInd().hashCode() );
         result = 37 * result + ( getOrderId() == null ? 0 : this.getOrderId().hashCode() );
         result = 37 * result + ( getReturnId() == null ? 0 : this.getReturnId().hashCode() );
         result = 37 * result + ( getOrderTsfNo() == null ? 0 : this.getOrderTsfNo().hashCode() );
         result = 37 * result + ( getReturnTsfNo() == null ? 0 : this.getReturnTsfNo().hashCode() );
         result = 37 * result + ( getRefDocumentId() == null ? 0 : this.getRefDocumentId().hashCode() );
         result = 37 * result + ( getFullUserName() == null ? 0 : this.getFullUserName().hashCode() );
         result = 37 * result + ( getAmtTotal() == null ? 0 : this.getAmtTotal().hashCode() );
         result = 37 * result + ( getRefDocumentNum() == null ? 0 : this.getRefDocumentNum().hashCode() );
         return result;
   }   


}


