package com.weigandtconsulting.javaschool.db.hibernate.entity;
// Generated Oct 28, 2015 4:51:35 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * ViewLookupDeliveryPointId generated by hbm2java
 */
public class ViewLookupDeliveryPointId  implements java.io.Serializable {


     private Short id;
     private String description;
     private String lookup;
     private Long customerId;
     private BigDecimal deliveryPoint;
     private BigDecimal locationId;
     private String idLookup;
     private String descriptionLookup;
     private String customerIdLookup;
     private String locationIdLookup;
     private String locationType;
     private BigDecimal physicalWh;
     private Boolean notDeliverableInd;

    public ViewLookupDeliveryPointId() {
    }

    public ViewLookupDeliveryPointId(Short id, String description, String lookup, Long customerId, BigDecimal deliveryPoint, BigDecimal locationId, String idLookup, String descriptionLookup, String customerIdLookup, String locationIdLookup, String locationType, BigDecimal physicalWh, Boolean notDeliverableInd) {
       this.id = id;
       this.description = description;
       this.lookup = lookup;
       this.customerId = customerId;
       this.deliveryPoint = deliveryPoint;
       this.locationId = locationId;
       this.idLookup = idLookup;
       this.descriptionLookup = descriptionLookup;
       this.customerIdLookup = customerIdLookup;
       this.locationIdLookup = locationIdLookup;
       this.locationType = locationType;
       this.physicalWh = physicalWh;
       this.notDeliverableInd = notDeliverableInd;
    }
   
    public Short getId() {
        return this.id;
    }
    
    public void setId(Short id) {
        this.id = id;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getLookup() {
        return this.lookup;
    }
    
    public void setLookup(String lookup) {
        this.lookup = lookup;
    }
    public Long getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }
    public BigDecimal getDeliveryPoint() {
        return this.deliveryPoint;
    }
    
    public void setDeliveryPoint(BigDecimal deliveryPoint) {
        this.deliveryPoint = deliveryPoint;
    }
    public BigDecimal getLocationId() {
        return this.locationId;
    }
    
    public void setLocationId(BigDecimal locationId) {
        this.locationId = locationId;
    }
    public String getIdLookup() {
        return this.idLookup;
    }
    
    public void setIdLookup(String idLookup) {
        this.idLookup = idLookup;
    }
    public String getDescriptionLookup() {
        return this.descriptionLookup;
    }
    
    public void setDescriptionLookup(String descriptionLookup) {
        this.descriptionLookup = descriptionLookup;
    }
    public String getCustomerIdLookup() {
        return this.customerIdLookup;
    }
    
    public void setCustomerIdLookup(String customerIdLookup) {
        this.customerIdLookup = customerIdLookup;
    }
    public String getLocationIdLookup() {
        return this.locationIdLookup;
    }
    
    public void setLocationIdLookup(String locationIdLookup) {
        this.locationIdLookup = locationIdLookup;
    }
    public String getLocationType() {
        return this.locationType;
    }
    
    public void setLocationType(String locationType) {
        this.locationType = locationType;
    }
    public BigDecimal getPhysicalWh() {
        return this.physicalWh;
    }
    
    public void setPhysicalWh(BigDecimal physicalWh) {
        this.physicalWh = physicalWh;
    }
    public Boolean getNotDeliverableInd() {
        return this.notDeliverableInd;
    }
    
    public void setNotDeliverableInd(Boolean notDeliverableInd) {
        this.notDeliverableInd = notDeliverableInd;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ViewLookupDeliveryPointId) ) return false;
		 ViewLookupDeliveryPointId castOther = ( ViewLookupDeliveryPointId ) other; 
         
		 return ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) )
 && ( (this.getDescription()==castOther.getDescription()) || ( this.getDescription()!=null && castOther.getDescription()!=null && this.getDescription().equals(castOther.getDescription()) ) )
 && ( (this.getLookup()==castOther.getLookup()) || ( this.getLookup()!=null && castOther.getLookup()!=null && this.getLookup().equals(castOther.getLookup()) ) )
 && ( (this.getCustomerId()==castOther.getCustomerId()) || ( this.getCustomerId()!=null && castOther.getCustomerId()!=null && this.getCustomerId().equals(castOther.getCustomerId()) ) )
 && ( (this.getDeliveryPoint()==castOther.getDeliveryPoint()) || ( this.getDeliveryPoint()!=null && castOther.getDeliveryPoint()!=null && this.getDeliveryPoint().equals(castOther.getDeliveryPoint()) ) )
 && ( (this.getLocationId()==castOther.getLocationId()) || ( this.getLocationId()!=null && castOther.getLocationId()!=null && this.getLocationId().equals(castOther.getLocationId()) ) )
 && ( (this.getIdLookup()==castOther.getIdLookup()) || ( this.getIdLookup()!=null && castOther.getIdLookup()!=null && this.getIdLookup().equals(castOther.getIdLookup()) ) )
 && ( (this.getDescriptionLookup()==castOther.getDescriptionLookup()) || ( this.getDescriptionLookup()!=null && castOther.getDescriptionLookup()!=null && this.getDescriptionLookup().equals(castOther.getDescriptionLookup()) ) )
 && ( (this.getCustomerIdLookup()==castOther.getCustomerIdLookup()) || ( this.getCustomerIdLookup()!=null && castOther.getCustomerIdLookup()!=null && this.getCustomerIdLookup().equals(castOther.getCustomerIdLookup()) ) )
 && ( (this.getLocationIdLookup()==castOther.getLocationIdLookup()) || ( this.getLocationIdLookup()!=null && castOther.getLocationIdLookup()!=null && this.getLocationIdLookup().equals(castOther.getLocationIdLookup()) ) )
 && ( (this.getLocationType()==castOther.getLocationType()) || ( this.getLocationType()!=null && castOther.getLocationType()!=null && this.getLocationType().equals(castOther.getLocationType()) ) )
 && ( (this.getPhysicalWh()==castOther.getPhysicalWh()) || ( this.getPhysicalWh()!=null && castOther.getPhysicalWh()!=null && this.getPhysicalWh().equals(castOther.getPhysicalWh()) ) )
 && ( (this.getNotDeliverableInd()==castOther.getNotDeliverableInd()) || ( this.getNotDeliverableInd()!=null && castOther.getNotDeliverableInd()!=null && this.getNotDeliverableInd().equals(castOther.getNotDeliverableInd()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
         result = 37 * result + ( getDescription() == null ? 0 : this.getDescription().hashCode() );
         result = 37 * result + ( getLookup() == null ? 0 : this.getLookup().hashCode() );
         result = 37 * result + ( getCustomerId() == null ? 0 : this.getCustomerId().hashCode() );
         result = 37 * result + ( getDeliveryPoint() == null ? 0 : this.getDeliveryPoint().hashCode() );
         result = 37 * result + ( getLocationId() == null ? 0 : this.getLocationId().hashCode() );
         result = 37 * result + ( getIdLookup() == null ? 0 : this.getIdLookup().hashCode() );
         result = 37 * result + ( getDescriptionLookup() == null ? 0 : this.getDescriptionLookup().hashCode() );
         result = 37 * result + ( getCustomerIdLookup() == null ? 0 : this.getCustomerIdLookup().hashCode() );
         result = 37 * result + ( getLocationIdLookup() == null ? 0 : this.getLocationIdLookup().hashCode() );
         result = 37 * result + ( getLocationType() == null ? 0 : this.getLocationType().hashCode() );
         result = 37 * result + ( getPhysicalWh() == null ? 0 : this.getPhysicalWh().hashCode() );
         result = 37 * result + ( getNotDeliverableInd() == null ? 0 : this.getNotDeliverableInd().hashCode() );
         return result;
   }   


}


