package com.weigandtconsulting.javaschool.db.hibernate.entity;
// Generated Oct 28, 2015 4:51:35 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * VolumeRebateDefinitions generated by hbm2java
 */
public class VolumeRebateDefinitions  implements java.io.Serializable {


     private BigDecimal id;
     private String description;
     private String status;
     private String definitionType;
     private String thresholdBaseType;
     private boolean automaticModeInd;
     private Date startDate;
     private Date endDate;
     private String currencyCode;
     private String defaultWholesaleSide;
     private String rowStatus;
     private String rowCreatedBy;
     private Serializable rowCreatedAt;
     private String rowUpdatedBy;
     private Serializable rowUpdatedAt;
     private String rowDeletedBy;
     private Serializable rowDeletedAt;
     private boolean excludePplInd;
     private boolean excludeFplInd;
     private boolean excludeCplInd;
     private boolean allCustomerInd;
     private boolean allPaymentTypeInd;
     private Set volumeRebateses = new HashSet(0);

    public VolumeRebateDefinitions() {
    }

	
    public VolumeRebateDefinitions(BigDecimal id, String description, String status, String definitionType, String thresholdBaseType, boolean automaticModeInd, Date startDate, Date endDate, String currencyCode, String defaultWholesaleSide, String rowStatus, String rowCreatedBy, Serializable rowCreatedAt, String rowUpdatedBy, Serializable rowUpdatedAt, boolean excludePplInd, boolean excludeFplInd, boolean excludeCplInd, boolean allCustomerInd, boolean allPaymentTypeInd) {
        this.id = id;
        this.description = description;
        this.status = status;
        this.definitionType = definitionType;
        this.thresholdBaseType = thresholdBaseType;
        this.automaticModeInd = automaticModeInd;
        this.startDate = startDate;
        this.endDate = endDate;
        this.currencyCode = currencyCode;
        this.defaultWholesaleSide = defaultWholesaleSide;
        this.rowStatus = rowStatus;
        this.rowCreatedBy = rowCreatedBy;
        this.rowCreatedAt = rowCreatedAt;
        this.rowUpdatedBy = rowUpdatedBy;
        this.rowUpdatedAt = rowUpdatedAt;
        this.excludePplInd = excludePplInd;
        this.excludeFplInd = excludeFplInd;
        this.excludeCplInd = excludeCplInd;
        this.allCustomerInd = allCustomerInd;
        this.allPaymentTypeInd = allPaymentTypeInd;
    }
    public VolumeRebateDefinitions(BigDecimal id, String description, String status, String definitionType, String thresholdBaseType, boolean automaticModeInd, Date startDate, Date endDate, String currencyCode, String defaultWholesaleSide, String rowStatus, String rowCreatedBy, Serializable rowCreatedAt, String rowUpdatedBy, Serializable rowUpdatedAt, String rowDeletedBy, Serializable rowDeletedAt, boolean excludePplInd, boolean excludeFplInd, boolean excludeCplInd, boolean allCustomerInd, boolean allPaymentTypeInd, Set volumeRebateses) {
       this.id = id;
       this.description = description;
       this.status = status;
       this.definitionType = definitionType;
       this.thresholdBaseType = thresholdBaseType;
       this.automaticModeInd = automaticModeInd;
       this.startDate = startDate;
       this.endDate = endDate;
       this.currencyCode = currencyCode;
       this.defaultWholesaleSide = defaultWholesaleSide;
       this.rowStatus = rowStatus;
       this.rowCreatedBy = rowCreatedBy;
       this.rowCreatedAt = rowCreatedAt;
       this.rowUpdatedBy = rowUpdatedBy;
       this.rowUpdatedAt = rowUpdatedAt;
       this.rowDeletedBy = rowDeletedBy;
       this.rowDeletedAt = rowDeletedAt;
       this.excludePplInd = excludePplInd;
       this.excludeFplInd = excludeFplInd;
       this.excludeCplInd = excludeCplInd;
       this.allCustomerInd = allCustomerInd;
       this.allPaymentTypeInd = allPaymentTypeInd;
       this.volumeRebateses = volumeRebateses;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getDefinitionType() {
        return this.definitionType;
    }
    
    public void setDefinitionType(String definitionType) {
        this.definitionType = definitionType;
    }
    public String getThresholdBaseType() {
        return this.thresholdBaseType;
    }
    
    public void setThresholdBaseType(String thresholdBaseType) {
        this.thresholdBaseType = thresholdBaseType;
    }
    public boolean isAutomaticModeInd() {
        return this.automaticModeInd;
    }
    
    public void setAutomaticModeInd(boolean automaticModeInd) {
        this.automaticModeInd = automaticModeInd;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public String getCurrencyCode() {
        return this.currencyCode;
    }
    
    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode;
    }
    public String getDefaultWholesaleSide() {
        return this.defaultWholesaleSide;
    }
    
    public void setDefaultWholesaleSide(String defaultWholesaleSide) {
        this.defaultWholesaleSide = defaultWholesaleSide;
    }
    public String getRowStatus() {
        return this.rowStatus;
    }
    
    public void setRowStatus(String rowStatus) {
        this.rowStatus = rowStatus;
    }
    public String getRowCreatedBy() {
        return this.rowCreatedBy;
    }
    
    public void setRowCreatedBy(String rowCreatedBy) {
        this.rowCreatedBy = rowCreatedBy;
    }
    public Serializable getRowCreatedAt() {
        return this.rowCreatedAt;
    }
    
    public void setRowCreatedAt(Serializable rowCreatedAt) {
        this.rowCreatedAt = rowCreatedAt;
    }
    public String getRowUpdatedBy() {
        return this.rowUpdatedBy;
    }
    
    public void setRowUpdatedBy(String rowUpdatedBy) {
        this.rowUpdatedBy = rowUpdatedBy;
    }
    public Serializable getRowUpdatedAt() {
        return this.rowUpdatedAt;
    }
    
    public void setRowUpdatedAt(Serializable rowUpdatedAt) {
        this.rowUpdatedAt = rowUpdatedAt;
    }
    public String getRowDeletedBy() {
        return this.rowDeletedBy;
    }
    
    public void setRowDeletedBy(String rowDeletedBy) {
        this.rowDeletedBy = rowDeletedBy;
    }
    public Serializable getRowDeletedAt() {
        return this.rowDeletedAt;
    }
    
    public void setRowDeletedAt(Serializable rowDeletedAt) {
        this.rowDeletedAt = rowDeletedAt;
    }
    public boolean isExcludePplInd() {
        return this.excludePplInd;
    }
    
    public void setExcludePplInd(boolean excludePplInd) {
        this.excludePplInd = excludePplInd;
    }
    public boolean isExcludeFplInd() {
        return this.excludeFplInd;
    }
    
    public void setExcludeFplInd(boolean excludeFplInd) {
        this.excludeFplInd = excludeFplInd;
    }
    public boolean isExcludeCplInd() {
        return this.excludeCplInd;
    }
    
    public void setExcludeCplInd(boolean excludeCplInd) {
        this.excludeCplInd = excludeCplInd;
    }
    public boolean isAllCustomerInd() {
        return this.allCustomerInd;
    }
    
    public void setAllCustomerInd(boolean allCustomerInd) {
        this.allCustomerInd = allCustomerInd;
    }
    public boolean isAllPaymentTypeInd() {
        return this.allPaymentTypeInd;
    }
    
    public void setAllPaymentTypeInd(boolean allPaymentTypeInd) {
        this.allPaymentTypeInd = allPaymentTypeInd;
    }
    public Set getVolumeRebateses() {
        return this.volumeRebateses;
    }
    
    public void setVolumeRebateses(Set volumeRebateses) {
        this.volumeRebateses = volumeRebateses;
    }




}


