package com.weigandtconsulting.javaschool.db.hibernate.entity;
// Generated Oct 28, 2015 4:51:35 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * VolumeRebates generated by hbm2java
 */
public class VolumeRebates  implements java.io.Serializable {


     private BigDecimal id;
     private VolumeRebateDefinitions volumeRebateDefinitions;
     private long customerId;
     private String status;
     private String wholesaleSide;
     private String currencyCode;
     private Date calcStartDate;
     private Date calcEndDate;
     private String changeReason;
     private String changeComments;
     private String comments;
     private String approvedBy;
     private Date approvedAt;
     private String rejectedBy;
     private Date rejectedAt;
     private String rowStatus;
     private String rowCreatedBy;
     private Serializable rowCreatedAt;
     private String rowUpdatedBy;
     private Serializable rowUpdatedAt;
     private String rowDeletedBy;
     private Serializable rowDeletedAt;

    public VolumeRebates() {
    }

	
    public VolumeRebates(BigDecimal id, VolumeRebateDefinitions volumeRebateDefinitions, long customerId, String status, String wholesaleSide, String currencyCode, Date calcStartDate, Date calcEndDate, String rowStatus, String rowCreatedBy, Serializable rowCreatedAt, String rowUpdatedBy, Serializable rowUpdatedAt) {
        this.id = id;
        this.volumeRebateDefinitions = volumeRebateDefinitions;
        this.customerId = customerId;
        this.status = status;
        this.wholesaleSide = wholesaleSide;
        this.currencyCode = currencyCode;
        this.calcStartDate = calcStartDate;
        this.calcEndDate = calcEndDate;
        this.rowStatus = rowStatus;
        this.rowCreatedBy = rowCreatedBy;
        this.rowCreatedAt = rowCreatedAt;
        this.rowUpdatedBy = rowUpdatedBy;
        this.rowUpdatedAt = rowUpdatedAt;
    }
    public VolumeRebates(BigDecimal id, VolumeRebateDefinitions volumeRebateDefinitions, long customerId, String status, String wholesaleSide, String currencyCode, Date calcStartDate, Date calcEndDate, String changeReason, String changeComments, String comments, String approvedBy, Date approvedAt, String rejectedBy, Date rejectedAt, String rowStatus, String rowCreatedBy, Serializable rowCreatedAt, String rowUpdatedBy, Serializable rowUpdatedAt, String rowDeletedBy, Serializable rowDeletedAt) {
       this.id = id;
       this.volumeRebateDefinitions = volumeRebateDefinitions;
       this.customerId = customerId;
       this.status = status;
       this.wholesaleSide = wholesaleSide;
       this.currencyCode = currencyCode;
       this.calcStartDate = calcStartDate;
       this.calcEndDate = calcEndDate;
       this.changeReason = changeReason;
       this.changeComments = changeComments;
       this.comments = comments;
       this.approvedBy = approvedBy;
       this.approvedAt = approvedAt;
       this.rejectedBy = rejectedBy;
       this.rejectedAt = rejectedAt;
       this.rowStatus = rowStatus;
       this.rowCreatedBy = rowCreatedBy;
       this.rowCreatedAt = rowCreatedAt;
       this.rowUpdatedBy = rowUpdatedBy;
       this.rowUpdatedAt = rowUpdatedAt;
       this.rowDeletedBy = rowDeletedBy;
       this.rowDeletedAt = rowDeletedAt;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public VolumeRebateDefinitions getVolumeRebateDefinitions() {
        return this.volumeRebateDefinitions;
    }
    
    public void setVolumeRebateDefinitions(VolumeRebateDefinitions volumeRebateDefinitions) {
        this.volumeRebateDefinitions = volumeRebateDefinitions;
    }
    public long getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(long customerId) {
        this.customerId = customerId;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getWholesaleSide() {
        return this.wholesaleSide;
    }
    
    public void setWholesaleSide(String wholesaleSide) {
        this.wholesaleSide = wholesaleSide;
    }
    public String getCurrencyCode() {
        return this.currencyCode;
    }
    
    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode;
    }
    public Date getCalcStartDate() {
        return this.calcStartDate;
    }
    
    public void setCalcStartDate(Date calcStartDate) {
        this.calcStartDate = calcStartDate;
    }
    public Date getCalcEndDate() {
        return this.calcEndDate;
    }
    
    public void setCalcEndDate(Date calcEndDate) {
        this.calcEndDate = calcEndDate;
    }
    public String getChangeReason() {
        return this.changeReason;
    }
    
    public void setChangeReason(String changeReason) {
        this.changeReason = changeReason;
    }
    public String getChangeComments() {
        return this.changeComments;
    }
    
    public void setChangeComments(String changeComments) {
        this.changeComments = changeComments;
    }
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }
    public String getApprovedBy() {
        return this.approvedBy;
    }
    
    public void setApprovedBy(String approvedBy) {
        this.approvedBy = approvedBy;
    }
    public Date getApprovedAt() {
        return this.approvedAt;
    }
    
    public void setApprovedAt(Date approvedAt) {
        this.approvedAt = approvedAt;
    }
    public String getRejectedBy() {
        return this.rejectedBy;
    }
    
    public void setRejectedBy(String rejectedBy) {
        this.rejectedBy = rejectedBy;
    }
    public Date getRejectedAt() {
        return this.rejectedAt;
    }
    
    public void setRejectedAt(Date rejectedAt) {
        this.rejectedAt = rejectedAt;
    }
    public String getRowStatus() {
        return this.rowStatus;
    }
    
    public void setRowStatus(String rowStatus) {
        this.rowStatus = rowStatus;
    }
    public String getRowCreatedBy() {
        return this.rowCreatedBy;
    }
    
    public void setRowCreatedBy(String rowCreatedBy) {
        this.rowCreatedBy = rowCreatedBy;
    }
    public Serializable getRowCreatedAt() {
        return this.rowCreatedAt;
    }
    
    public void setRowCreatedAt(Serializable rowCreatedAt) {
        this.rowCreatedAt = rowCreatedAt;
    }
    public String getRowUpdatedBy() {
        return this.rowUpdatedBy;
    }
    
    public void setRowUpdatedBy(String rowUpdatedBy) {
        this.rowUpdatedBy = rowUpdatedBy;
    }
    public Serializable getRowUpdatedAt() {
        return this.rowUpdatedAt;
    }
    
    public void setRowUpdatedAt(Serializable rowUpdatedAt) {
        this.rowUpdatedAt = rowUpdatedAt;
    }
    public String getRowDeletedBy() {
        return this.rowDeletedBy;
    }
    
    public void setRowDeletedBy(String rowDeletedBy) {
        this.rowDeletedBy = rowDeletedBy;
    }
    public Serializable getRowDeletedAt() {
        return this.rowDeletedAt;
    }
    
    public void setRowDeletedAt(Serializable rowDeletedAt) {
        this.rowDeletedAt = rowDeletedAt;
    }




}


